options:
  logging: CLOUD_LOGGING_ONLY

steps:
  # Step 1: Zapisz sekrety bezpośrednio w katalogu głównym
  - name: 'ubuntu'
    secretEnv: ['DOTENV', 'FIREBASE_KEY']
    entrypoint: 'bash'
    args:
      - -c
      - |
        echo "Saving secrets into files..."
        echo "$$DOTENV" > .env
        mkdir -p interior_planner
        echo "$$FIREBASE_KEY" > interior_planner/firebase-adminsdk.json

  # Step 2: Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/interior-planner-api', '.']

  # Step 3: Push image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/interior-planner-api']

  # Step 4: Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'interior-planner-api'
      - '--image=gcr.io/$PROJECT_ID/interior-planner-api'
      - '--region=europe-central2'
      - '--platform=managed'
      - '--allow-unauthenticated'

availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/django-env/versions/latest
      env: 'DOTENV'
    - versionName: projects/$PROJECT_ID/secrets/firebase-key/versions/latest
      env: 'FIREBASE_KEY'
