options:
  logging: CLOUD_LOGGING_ONLY

steps:
  - name: 'gcr.io/cloud-builders/docker'
    secretEnv: ['_DOTENV', '_FIREBASE_KEY']
    entrypoint: 'bash'
    args:
      - -c
      - |
        echo "$_DOTENV" > .env
        echo "$_FIREBASE_KEY" > firebase-adminsdk.json
        docker build -t gcr.io/supple-century-454616-u8/interior-planner-api .

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/supple-century-454616-u8/interior-planner-api']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'interior-planner-api'
      - '--image=gcr.io/supple-century-454616-u8/interior-planner-api'
      - '--region=europe-central2'
      - '--platform=managed'
      - '--allow-unauthenticated'

availableSecrets:
  secretManager:
    - versionName: projects/supple-century-454616-u8/secrets/django-env/versions/latest
      env: '_DOTENV'
    - versionName: projects/supple-century-454616-u8/secrets/firebase-key/versions/latest
      env: '_FIREBASE_KEY'