options:
  logging: CLOUD_LOGGING_ONLY

steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-f', 'interion_planner/Dockerfile', '-t', 'gcr.io/$PROJECT_ID/interior-planner-api', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/interior-planner-api']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'interior-planner-api'
      - '--image=gcr.io/$PROJECT_ID/interior-planner-api'
      - '--region=europe-central2'
      - '--platform=managed'
      - '--allow-unauthenticated'
